#!/bin/bash
export PATH=/root/.cabal/bin:/job/bin:$PATH
export HOME=/root

function cleanup(){
    find /job -maxdepth 1 -mindepth 1 -not -name output -exec rm -rf {} +
}

function job(){
    cd /tmp/
    tar -xjf /job/ghc-GHC_VERSION.tar.bz2
    cd /tmp/ghc-GHC_VERSION
    ./configure --prefix=/opt
    echo "EXIT STATUS $?"
    make install
    echo "EXIT STATUS $?"
    cleanup
    cd /job/output
    tar -cf opt_ghc-GHC_VERSION.tar /opt
    cp -r /opt /job/output
}

job > /job/output/output.txt 2>&1
